apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidly-deployment
  namespace: vidly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vidly
  template:
    metadata:
      labels:
        app: vidly
    spec:
      containers:
      - name: nginx
        image: docker.io/nickdraper/vidly-api:latest
        ports:
        - containerPort: 8000
